version: '3'

services:
  nginx:
    build:
      context: web/docker
      dockerfile: nginx.docker
    volumes:
      - ./web:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: web/docker
      dockerfile: php-fpm.docker
    volumes:
      - ./web:/app
      - ../opt/mcpe-data:/app/data
    depends_on:
      - postgres

  php-cli:
    build:
      context: web/docker
      dockerfile: php-cli.docker
    volumes:
      - ./web:/app
      - ../opt/mcpe-data:/app/data
      - composer:/root/.composer/cache
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

volumes:
  postgres:
  composer: