version: '3'

services:
  nginx:
    build:
      context: web/docker
      dockerfile: nginx.docker
    volumes:
      - ./web:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: web/docker
      dockerfile: php-fpm.docker
    volumes:
      - ./web:/app
      - ../opt/mcpe-data:/app/data

  php-cli:
    build:
      context: web/docker
      dockerfile: php-cli.docker
    volumes:
      - ./web:/app
      - ../opt/mcpe-data:/app/data
      - composer:/root/.composer/cache
    tty: true

volumes:
  composer: